//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "chapter_iden")]
pub struct Model {
    pub author: Option<i32>,
    pub book: Option<i32>,
    pub pubic: Option<bool>,
    pub published: Option<DateTime>,
    pub text: Option<String>,
    pub title: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::book_iden::Entity",
        from = "Column::Book",
        to = "super::book_iden::Column::BookId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    BookIden,
    #[sea_orm(
        belongs_to = "super::user_iden::Entity",
        from = "Column::Author",
        to = "super::user_iden::Column::UserId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    UserIden,
}

impl Related<super::book_iden::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookIden.def()
    }
}

impl Related<super::user_iden::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserIden.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
