//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

pub use super::book_iden::Entity as BookIden;
pub use super::chapter_iden::Entity as ChapterIden;
pub use super::user_iden::Entity as UserIden;
